[tool.poetry]
name = "github-powered-pypi"
version = "0.1.0"
description = "A private PyPI server powered by GitHub."
license = "MIT"
authors = ["huntzhan <huntzhan.dev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
# TODO: Will support all python versions in the future
# by using https://github.com/python-best-practices/wheel-compiler
python = "^3.7"
flask = "^1.1.1"
requests = "^2.22.0"
PyGithub = "^1.45"
toml = "^0.10.0"
filelock = "^3.0.12"
shortuuid = "^0.5.0"
fire = "^0.2.1"
Jinja2 = "^2.11.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
yapf = "^0.29.0"
pylint = "^2.4.4"

[tool.poetry.scripts]
github_upload_package = "github_powered_pypi.pkg_repos.github:github_upload_package_cli"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
